[workspace]
members = [
    "node",
    "pallets/collectibles",
    "pallets/pallet-randomness-collective-flip",
    "pallets/template",
    "runtime",
]
resolver = "2"
[profile.release]
panic = "unwind"
